sudo: required

language: csharp

services:
  - docker

before_install:
  - docker build -t webapp:test -f ./dockerfile/test .

script:
  - export CD_PATH = $PWD/publish
  - docker run -it --rm -v $PWD/publish:/root/publish -v $PWD/packages:/root/.nuget/packages webapp:test
  
after_success:
  - print $CD_PATH
  - cd ./$CD_PATH
  - docker build -t webapp:release -f ./dockerfile/release .
  - docker tag webapp:release cedmartel/webapp:latest
  - docker docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker docker push cedmartel/webapp:latest
