sudo: required

language: csharp

services:
  - docker

before_install:
  - docker build -t webapp:test -f ./dockerfile/test .


script:
  - docker run -it --rm -v $PWD/publish:/root/publish -v $PWD/packages:/root/.nuget/packages webapp:test

after_success:
  - docker run -it --rm -p 8080:5000 webapp:release
  - docker build -t webapp:release -f ./dockerfile/release .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag webapp:release cedmartel/webapp:latest
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push cedmartel/webapp:latest;
    fi

deploy:
  - scp -0 StrictHostKeyChecking=no ./scripts/getReleaseFromDockerHubAndStart.sh u1334019@159.203.33.172
  - ssh u1334019@159.203.33.172 "chmod +x getReleaseFromDockerHubAndStart.sh"
  - ssh u1334019@159.203.33.172 "sh getReleaseFromDockerHubAndStart.sh"
